# Generated by Django 5.0.1 on 2024-02-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterModelTable(
            name='variants',
            table='variant',
        ),
    ]
