# Generated by Django 4.2.4 on 2023-08-25 13:49

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shop.models.ProductImage.dirName),
        ),
    ]
