# Generated by Django 5.0.1 on 2024-02-03 11:46

import shop.models.sub_category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_variants_options_alter_variants_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_men',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to=shop.models.sub_category.SubCategory.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_women',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to=shop.models.sub_category.SubCategory.get_image_upload_path),
        ),
    ]
