# Generated by Django 5.0.1 on 2024-01-30 13:01

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_price_product_current_price_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=5000, upload_to=shop.models.ProductImage.get_image_upload_path),
        ),
    ]
