# Generated by Django 5.0.1 on 2024-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subcategory_image_men_subcategory_image_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='card_view',
            field=models.BooleanField(default=False),
        ),
    ]
