# Generated by Django 4.2.4 on 2023-09-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
