# Generated by Django 5.0.1 on 2024-02-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_subcategory_card_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='image_men',
            new_name='image_primary',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='image_women',
            new_name='image_secondary',
        ),
    ]
