# Generated by Django 4.2.4 on 2023-08-27 10:42

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=shop.models.ProductImage.dirName),
        ),
    ]
