# Generated by Django 4.2.4 on 2023-09-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='products',
        ),
    ]
